version: '3.8'

services:
  financebot:
    build: .
    container_name: financebot
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - TELEGRAM_BOT_TOKEN=8776486577:AAEwIU6KG7BSg9XyRRPdDMq29a7EvH3D7Us